### ISSUE TITLE
Requesting contribution rights to this repository

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie-store#7]
Hi NPBruce,

There are not many people with sufficient rights to add scenarios to Valkyrie & Decent. This is obviously done for a good reason but it also means that this activity may get delayed/blocked by the availability of you or scrubbless.

I would like to request contribution rights to this repository to support you with this activity. The manifests do not look very complicated, and scrubbles offered to explain to me how it works.

Best regards,
Anton

**Comment by NPBruce** [comment]
Added.
